# ---------------------------------------------------------
# [Q3] Return all articles with property pages, month, isbn.
# pages is satisfied by 96%, month by 0.6%, and isbn by none. 
# (combined original queries 3a-c)
# Star query with few joins (0 results @ 50k)
# ---------------------------------------------------------
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bench: <http://localhost/vocabulary/bench/>
PREFIX swrc:  <http://swrc.ontoware.org/ontology#>

SELECT ?article ?pages ?month ?isbn
WHERE {
  ?article rdf:type bench:Article .
  ?article swrc:pages ?pages.
  ?article swrc:month ?month.
  ?article swrc:isbn  ?isbn
}